### ISSUE TITLE
Import under linux firefox with wayland failed

### ISSUE THREAD

**Issue by YoSiJo** [EddieDover/fvtt-player-achievements#10]
**Describe the bug**
The Import function don't find the clipboard content.

**To Reproduce**
1. Export Achievements to clipboard
2. Delete Achievements
3. Use the Import function

**Expected behavior**
The Achievements are imported

**Screenshots**
![image](https://github.com/EddieDover/fvtt-player-achievements/assets/42408075/60998df8-a368-4233-8440-a965c10f6bce)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser FireDox-Dev
 - Version 120.0b9 (64-Bit)

**Additional context**

```text
Uncaught (in promise) TypeError: navigator.clipboard.readText is not a function
[Detected 1 package: fvtt-player-achievements]
    onImportAchievements achievement-form.js:173
    jQuery 9
    activateListeners achievement-form.js:136
    _render foundry.js:5842
    _render foundry.js:6532
    render foundry.js:5769
    toggleAchievementScreen fvtt-player-achievements.js:85
    <anonymous> fvtt-player-achievements.js:252
```

**Comment by EddieDover** [comment]
I'm currently on vacation until Wednesday, but I will investigate this beforehand to see if it's possibly just a Firefox issue.  Mind if I reach out in the future, just in case I can't reproduce? I won't be able to spin up an Arch container until Friday most likely.

**Comment by EddieDover** [comment]
Okay the issue is with Firefox itself and its clipboard handling functions. Just to make things easy, I'll have to rework the import export to not directly affect the clipboard and instead give users a place to copy and paste data from a separate popup. 

Expect the fix in today.

**Comment by EddieDover** [comment]
Sorry this took so long. I had to work off of a tablet and didn't have a dev environment setup. Took a bit of tinkering.

**Comment by YoSiJo** [comment]
Long? 
I set up an issue and expect it to have to go through meetings, ideas, debugging, desperation phases, etc. ;)
That went smoothly and I am very grateful for the solution.
Thank you very much.
