### ISSUE TITLE
Add effects on achievement and way to check if an achievement is unlocked

### ISSUE THREAD

**Issue by tirzah2** [EddieDover/fvtt-player-achievements#32]
Hi!
it would be great if it was possible to add an effect (DAE, DFRE CE) if an actor has unlocked an achievement. 
It would also be great if it was possible to check if an actor has specific achievement (return true) to be used in conjunction with BABONUS by Zhell. 

thank you very much!

**Comment by EddieDover** [comment]
Let me research how to best tackle this and I'll see about getting it done soon.

**Comment by EddieDover** [comment]
Next release will include an API and some Hooks, so that other plugins can access fvtt-pa's core functionality. This doesn't exactly resolve this particular issue but it opens the doors to supplemental plugins that can do the job (which I don't mind working on when I have time.)
