### ISSUE TITLE
Consider auto-generating UUIDs instead of asking players for one.

### ISSUE THREAD

**Issue by EddieDover** [EddieDover/fvtt-player-achievements#44]
Given that I want this plugin to be as easy to use as possible, it's not the worst idea to remove or replace the unique id field. It's existence only serves a backend purpose and moving everything under the hood shouldn't break any existing functionality.

I'll test this and see how difficult it would be to implement.

**Comment by EddieDover** [comment]
Making it so that an achievement ID is autogenerated if it's not provided probably is the best route. 

This may mean I need to adjust some of the API calls to either operate the same way.  This may mean that calls to the API to create an achievement will need to be adjusted to return the Achievement ID in case it was auto generated.

**Comment by brunocalado** [comment]
Yes, please. The user don't need to set the ID
