### ISSUE TITLE
[Feature]:  Add a global override for base achievement sound

### ISSUE THREAD

**Issue by EddieDover** [EddieDover/fvtt-player-achievements#55]
GMs should be able to set a default sound for achievements, that overrides the built-in default, allowing the per-achievement override to be a special case.

Also, research is needed to see if sounds can be passed through the interface channel so the built-in volume sliders would work rather than needing our own.

**Comment by brunocalado** [comment]
Yes, I would like to set a default sound in settings for all achievements. This would allow to change the sound of all achievements easily.
