### ISSUE TITLE
[Bug]: Achievements Become Uneditable

### ISSUE THREAD

**Issue by Prismatic-Empress** [EddieDover/fvtt-player-achievements#61]
### What happened?

After editing an achievement, or in some cases, after giving an achievement out to players it becomes impossible to edit an achievement. When I attempt to save the changes they are reverted. Additionally the tags are not visible for achievements that cannot be edited, although these achievements still appear under their tag when filtering. This does not happen to all achievements and I have been able to create new achievements and most function properly. It is still possible to give and revoke one of these "locked" achievements from players. 

Foundry is on Version 11 Stable 315
The system is Pathfinder Second Edition 5.14.3
Player Achievements is on version 1.4.1
socketlib is on version 1.0.13

### What type of foundry hosting were you using?

3rd-Party Hosted

**Comment by EddieDover** [comment]
Are you seeing any messages in your console when this happens?

**Comment by Prismatic-Empress** [comment]
![image](https://github.com/EddieDover/fvtt-player-achievements/assets/153450384/5ad38e1d-89b8-4b48-991e-a8da909d515d)
The first error appears when I click edit on the achievement. The second error appears when I attempt to save it.
